### ISSUE TITLE
Proposal: support collapsing the root and starting with the pane collapsed

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#19]
Sometimes (when presenting to a client for example) it is useful to put the focus on the actual developed piece instead of the controls pane. In these situations, it's ideal if the whole pane starts collapsed, and only if a user wants, he can open it and interact with the controls.

This is also useful in situations where you have waaay to many properties that it covers the full span fo the window height, although this can be managed with subfolders: 

<img src="https://user-images.githubusercontent.com/7217420/103023232-dbf50b80-454d-11eb-9270-04d33fdf9b08.png" width="200" />

**Comment by dbismut** [comment]
I believe this is achieved through `<Leva collapsed />`
