### ISSUE TITLE
Making fields controllable

### ISSUE THREAD

**Issue by gsimone** [gsimone/leva#21]
We can do so in a rough, non-user-friendly way by just exporting setValueAtPath and letting the user figure out the current path. This works on the assumption that the type of user that needs this, would know what to do.

We can think of ways to make this a first class thing

**Comment by dbismut** [comment]
This is now done, the reacty / pmdnrs way by submitting the inputs in a function.
So:

```js
const [values, store, set] = useControls(() => ({ /* inputs */ }))
```

`set` allows you to imperatively set the values returned by the hook:

```js
set({ [inputKey]: newValue })
```
