### ISSUE TITLE
Leva doesn't get latest state value

### ISSUE THREAD

**Issue by marcelpi** [gsimone/leva#260]
Hi there,

I've been playing with Leva lately and noticed it sometimes does not get the current value of a state, but is hung on one of the last values.

Take this simple counter example. If I'm clicking on the 'Click me' button the count increases.
If you look in the console the current value is displayed, while if I click on the Leva button another one is printed.

Here's the link: https://codesandbox.io/s/leva-state-experiment-v0rso

![Screen Shot 2021-10-08 at 17 07 14](https://user-images.githubusercontent.com/7136479/136572077-1f2d1cb0-dc94-43bf-9f5b-2d1578d71694.png)

**Comment by dbismut** [comment]
Leva's schema is not reactive to prevent unnecessary re-renders. But you can pass a value as a dependency.

https://codesandbox.io/s/leva-state-experiment-forked-jfqcr?file=/src/App.js
