### ISSUE TITLE
Range slider: redesign with half the slider

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#50]
Redesign the range slider so it's like a normal slider but cut in half.

### Current situation
<img width="232" alt="Screenshot_2021-02-01_at_11 47 47" src="https://user-images.githubusercontent.com/7217420/106453346-728be500-6489-11eb-8c39-45f8727ac78d.png">

### Ideal situation 
<img width="230" src="https://user-images.githubusercontent.com/7217420/106453452-a49d4700-6489-11eb-984c-390398b54d22.png" />

**Optional**: 🎊confetti pop when the two halves meet.

**Comment by dbismut** [comment]
Should be fixed: https://github.com/gsimone/leva/pull/49/commits/7affde7969b432481c2500c9f5fcb8b0e6633438 (confetti not added though, didn't make the cut but we have a draft.

https://user-images.githubusercontent.com/5003380/106467319-c18f4580-649c-11eb-81cb-b40473254d63.mov
