### ISSUE TITLE
Slider: make it narrower

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#51]
I don't know why but it felt better than when it was narrower, it felt more precise.

https://user-images.githubusercontent.com/7217420/106453838-2db47e00-648a-11eb-9ce7-c1b57196429d.mov

**Bug in the video at 0:09** when I click on the other end of the slider, the slider rectangle doesn't go where I clicked, but rater a bit on the left.

**Comment by dbismut** [comment]
Should be fixed in https://github.com/gsimone/leva/pull/49/commits/7affde7969b432481c2500c9f5fcb8b0e6633438
