### ISSUE TITLE
Label: make the copy icon transform into a ✅ when clicked

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#53]
The copy icon should transform into a ✅  to give the user feedback that the field has been copied.

### Current situation 

https://user-images.githubusercontent.com/7217420/106454521-28a3fe80-648b-11eb-902f-8409402a9a7f.mov

**Comment by dbismut** [comment]
Done in https://github.com/gsimone/leva/pull/49/commits/2c1252f249860df05a914a03e0887119675991bb
