### ISSUE TITLE
File input: when loading an image the input doesn't expand

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#55]
### Current

![image](https://user-images.githubusercontent.com/7217420/106455281-432aa780-648c-11eb-8557-c4a542cdd01f.png)

### Ideal 

The input should expand and reveal the whole image instead.

Also the `x` is missing a `/`?

**Comment by dbismut** [comment]
Fixed in https://github.com/gsimone/leva/pull/49/commits/2c81f635ccf22c668c98903de8d812197ba3cb0f
