### ISSUE TITLE
Header: consider new design

### ISSUE THREAD

**Issue by marcofugaro** [gsimone/leva#57]
I made some mockups that solve some UX issues the header currently has:

| Branding | No branding | No nothing |
-----------|--------------|--------------
| <img src="https://user-images.githubusercontent.com/7217420/106469532-b4c02100-649f-11eb-845f-be8d3033d894.png" /> | <img src="https://user-images.githubusercontent.com/7217420/106469555-bbe72f00-649f-11eb-8765-f3f39cbdbdca.png" /> | <img src="https://user-images.githubusercontent.com/7217420/106469590-c4d80080-649f-11eb-8f2f-c19006a964b6.png" /> |

advantages:
- the search becomes a secondary action, since most users wouldn't use it (if there are only a few inputs for example)
- end users know it's draggable now
- triangle is there to show that it can be collapsed and also uncollapsed if it starts already collapsed

**Comment by dbismut** [comment]
Fixed in #49!
