### ISSUE TITLE
react-colorful v5

### ISSUE THREAD

**Issue by omgovich** [gsimone/leva#70]
Hi, sorry for bothering you, but I have news that might be helpful for this project:

react-colorful `v5` was just released and it doesn't require importing CSS-file.
It means that you can remove all CSS code you copied from the original repo.
Just use the CSS-in-JS solution of your choice to override the styles you need.

https://github.com/omgovich/react-colorful/releases

**Comment by dbismut** [comment]
This is awesome! We were discussing this just yesterday :)
I'm going to try to integrate react-colorful v5 later today!

**Comment by omgovich** [comment]
👍 Let me know if you'll have any issues.

**Comment by omgovich** [comment]
BTW: Don't you have any online demo where I can take a screenshot of the UI?

I would like to mention this project in the react-colorful's README:
https://github.com/omgovich/react-colorful#projects-using-react-colorful

**Comment by dbismut** [comment]
Done! Just pushed v5 in master and removed the css code, much cleaner now!

The lib is still under development and not really ready for public release yet, but here's a working sandbox https://codesandbox.io/s/leva-busy-ge7t1 (it's a few commits behind)

Thanks again for react-colorful, amazing lib.
